services:
  app:
    build: .
    container_name: pastebin-lite-app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true